[pytest]
testpaths = tests          # find tests in folder tests/
python_files = test_*.py   # files start with test_
python_classes = Test*     # classes start with с Test
python_functions = test_*  # functions start with с test_
addopts = -v --tb=short    # -v = verbose, --tb=short = short traceback